# scalar Time

type Account {
  username: String!
  fullname: String!
  image: String

  # posts: [Post]!
  createdAt: String!
}

type Post {
  title: String!
  content: String!
  slug: String!
  draft: Boolean!
  likes: Int!

  tags: [Tag]!
  comments: [Comment]!
  account: Account
  # createdAt: Time!
  # updatedAt: Time!
}

type Tag {
  name: String!
  description: String!
}

type Comment {
  content: String!
  username: String!
}

type Query {
  account: Account!
}

type Mutation {
  updateAccount(input: UpdateAccountInput!): Account!
}

input UpdateAccountInput {
  username: String
  fullname: String
  image: String
}
